"""Add latency and status_code to ai_token_usage

Revision ID: 834d9b7f264f
Revises: 68596c43178a
Create Date: 2026-07-31 21:17:51.651196+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "834d9b7f264f"
down_revision = "68596c43178a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ai_token_usage",
        sa.Column("latency_ms", sa.Float(), nullable=False, server_default="0.0"),
    )
    op.add_column(
        "ai_token_usage",
        sa.Column("status_code", sa.Integer(), nullable=False, server_default="200"),
    )
    op.alter_column(
        "tenants",
        "billing_cycle",
        existing_type=sa.VARCHAR(length=20),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "tenants",
        "mrr",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tenants",
        "mrr",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=sa.text("'0'::double precision"),
        existing_nullable=False,
    )
    op.alter_column(
        "tenants",
        "billing_cycle",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'monthly'::character varying"),
        existing_nullable=False,
    )
    op.drop_column("ai_token_usage", "status_code")
    op.drop_column("ai_token_usage", "latency_ms")
    # ### end Alembic commands ###
