"""Add AI Ops models

Revision ID: a47402aa4424
Revises: 9ca1cf003af2
Create Date: 2026-08-01 11:17:00.103435+00:00

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a47402aa4424"
down_revision = "9ca1cf003af2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_prompt_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("user_prompt_template", sa.Text(), nullable=False),
        sa.Column("variables", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_ai_prompt_templates_id"), "ai_prompt_templates", ["id"], unique=False,
    )
    op.create_table(
        "ai_providers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("logo_url", sa.String(), nullable=True),
        sa.Column("base_url", sa.String(), nullable=False),
        sa.Column("api_key_secret", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ONLINE", "OFFLINE", "DEGRADED", "MAINTENANCE", name="providerstatus",
            ),
            nullable=True,
        ),
        sa.Column("health_score", sa.Float(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("environment", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_providers_id"), "ai_providers", ["id"], unique=False)
    op.create_index(op.f("ix_ai_providers_name"), "ai_providers", ["name"], unique=True)
    op.create_table(
        "ai_models",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("model_id_string", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "CHAT",
                "REASONING",
                "EMBEDDING",
                "VISION",
                "IMAGE_GEN",
                "SPEECH_TO_TEXT",
                "TEXT_TO_SPEECH",
                "OCR",
                "FORECASTING",
                name="modeltype",
            ),
            nullable=True,
        ),
        sa.Column("context_window", sa.Integer(), nullable=False),
        sa.Column(
            "input_cost_per_1k", sa.Numeric(precision=10, scale=6), nullable=False,
        ),
        sa.Column(
            "output_cost_per_1k", sa.Numeric(precision=10, scale=6), nullable=False,
        ),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["provider_id"], ["ai_providers.id"], ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_models_id"), "ai_models", ["id"], unique=False)
    op.create_index(op.f("ix_ai_models_name"), "ai_models", ["name"], unique=False)
    op.create_table(
        "ai_routing_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_type", sa.String(), nullable=False),
        sa.Column("primary_model_id", sa.UUID(), nullable=True),
        sa.Column("fallback_model_id", sa.UUID(), nullable=True),
        sa.Column("timeout_ms", sa.Integer(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["fallback_model_id"], ["ai_models.id"], ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["primary_model_id"], ["ai_models.id"], ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_type"),
    )
    op.create_index(
        op.f("ix_ai_routing_rules_id"), "ai_routing_rules", ["id"], unique=False,
    )
    op.create_table(
        "ai_usage_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("model_id", sa.UUID(), nullable=True),
        sa.Column("provider_id", sa.UUID(), nullable=True),
        sa.Column("task_type", sa.String(), nullable=True),
        sa.Column("tokens_prompt", sa.Integer(), nullable=True),
        sa.Column("tokens_completion", sa.Integer(), nullable=True),
        sa.Column("tokens_total", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["model_id"], ["ai_models.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["provider_id"], ["ai_providers.id"], ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_usage_logs_created_at"),
        "ai_usage_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_ai_usage_logs_id"), "ai_usage_logs", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ai_usage_logs_id"), table_name="ai_usage_logs")
    op.drop_index(op.f("ix_ai_usage_logs_created_at"), table_name="ai_usage_logs")
    op.drop_table("ai_usage_logs")
    op.drop_index(op.f("ix_ai_routing_rules_id"), table_name="ai_routing_rules")
    op.drop_table("ai_routing_rules")
    op.drop_index(op.f("ix_ai_models_name"), table_name="ai_models")
    op.drop_index(op.f("ix_ai_models_id"), table_name="ai_models")
    op.drop_table("ai_models")
    op.drop_index(op.f("ix_ai_providers_name"), table_name="ai_providers")
    op.drop_index(op.f("ix_ai_providers_id"), table_name="ai_providers")
    op.drop_table("ai_providers")
    op.drop_index(op.f("ix_ai_prompt_templates_id"), table_name="ai_prompt_templates")
    op.drop_table("ai_prompt_templates")
    # ### end Alembic commands ###
