"""Add API Gateway models

Revision ID: c884bdec6eb8
Revises: 834d9b7f264f
Create Date: 2026-08-01 09:30:58.360465+00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c884bdec6eb8"
down_revision = "834d9b7f264f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_integrations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("health_status", sa.String(length=20), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider"),
    )
    op.create_table(
        "api_rate_limits",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("requests_per_minute", sa.Integer(), nullable=False),
        sa.Column("burst_capacity", sa.Integer(), nullable=False),
        sa.Column("monthly_quota", sa.Integer(), nullable=False),
        sa.Column("current_period_usage", sa.Integer(), nullable=False),
        sa.Column("alerts_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id"),
    )
    op.create_table(
        "api_request_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("api_key_id", sa.UUID(), nullable=True),
        sa.Column("endpoint", sa.String(length=255), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("payload_size_bytes", sa.Integer(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("version", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["api_key_id"], ["api_keys.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_api_request_logs_api_key_id"),
        "api_request_logs",
        ["api_key_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_api_request_logs_created_at"),
        "api_request_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_api_request_logs_endpoint"),
        "api_request_logs",
        ["endpoint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_api_request_logs_status_code"),
        "api_request_logs",
        ["status_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_api_request_logs_workspace_id"),
        "api_request_logs",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "oauth_clients",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("client_name", sa.String(length=255), nullable=False),
        sa.Column("client_id", sa.String(length=100), nullable=False),
        sa.Column("client_secret_hash", sa.String(length=255), nullable=False),
        sa.Column("redirect_uris", sa.JSON(), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_oauth_clients_client_id"), "oauth_clients", ["client_id"], unique=True
    )
    op.create_index(
        op.f("ix_oauth_clients_workspace_id"),
        "oauth_clients",
        ["workspace_id"],
        unique=False,
    )
    op.alter_column(
        "ai_token_usage",
        "latency_ms",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "ai_token_usage",
        "status_code",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ai_token_usage",
        "status_code",
        existing_type=sa.INTEGER(),
        server_default=sa.text("200"),
        existing_nullable=False,
    )
    op.alter_column(
        "ai_token_usage",
        "latency_ms",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=sa.text("'0'::double precision"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_oauth_clients_workspace_id"), table_name="oauth_clients")
    op.drop_index(op.f("ix_oauth_clients_client_id"), table_name="oauth_clients")
    op.drop_table("oauth_clients")
    op.drop_index(
        op.f("ix_api_request_logs_workspace_id"), table_name="api_request_logs"
    )
    op.drop_index(
        op.f("ix_api_request_logs_status_code"), table_name="api_request_logs"
    )
    op.drop_index(op.f("ix_api_request_logs_endpoint"), table_name="api_request_logs")
    op.drop_index(op.f("ix_api_request_logs_created_at"), table_name="api_request_logs")
    op.drop_index(op.f("ix_api_request_logs_api_key_id"), table_name="api_request_logs")
    op.drop_table("api_request_logs")
    op.drop_table("api_rate_limits")
    op.drop_table("api_integrations")
    # ### end Alembic commands ###
