"""Add auth models

Revision ID: 1a69c2ebe523
Revises: 3f1e5a230e9c
Create Date: 2026-08-08 07:33:30.315342+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a69c2ebe523'
down_revision = '3f1e5a230e9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('trigger_type', sa.String(length=100), nullable=False),
    sa.Column('trigger_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('execution_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('framework', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('controls_passed', sa.Integer(), nullable=False),
    sa.Column('controls_failed', sa.Integer(), nullable=False),
    sa.Column('last_audit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_audit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('framework')
    )
    op.create_table('feature_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_key'), 'feature_flags', ['key'], unique=True)
    op.create_table('integration_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('auth_type', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error_rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_created_at'), 'security_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_security_events_event_type'), 'security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_events_ip_address'), 'security_events', ['ip_address'], unique=False)
    op.create_table('threat_intelligence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indicator_value', sa.String(length=255), nullable=False),
    sa.Column('indicator_type', sa.String(length=50), nullable=False),
    sa.Column('threat_type', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('reputation_score', sa.Integer(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_intelligence_indicator_value'), 'threat_intelligence', ['indicator_value'], unique=True)
    op.create_table('feature_experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flag_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('traffic_allocation', sa.Integer(), nullable=False),
    sa.Column('variation_a_success', sa.Integer(), nullable=False),
    sa.Column('variation_b_success', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['flag_id'], ['feature_flags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_rollouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flag_id', sa.UUID(), nullable=False),
    sa.Column('rollout_percentage', sa.Integer(), nullable=False),
    sa.Column('target_roles', sa.JSON(), nullable=True),
    sa.Column('target_organizations', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['flag_id'], ['feature_flags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('request_method', sa.String(length=20), nullable=False),
    sa.Column('endpoint', sa.String(length=2048), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integration_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_logs_created_at'), 'integration_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_integration_logs_integration_id'), 'integration_logs', ['integration_id'], unique=False)
    op.create_table('login_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('browser', sa.String(length=100), nullable=False),
    sa.Column('os', sa.String(length=100), nullable=False),
    sa.Column('device', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_history_user_id'), 'login_history', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.add_column('audit_logs', sa.Column('severity', sa.String(length=50), nullable=False))
    op.add_column('audit_logs', sa.Column('module', sa.String(length=100), nullable=False))
    op.add_column('audit_logs', sa.Column('old_value', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('new_value', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('correlation_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_module'), 'audit_logs', ['module'], unique=False)
    # op.alter_column('tenants', 'db_connection_type',
    #            existing_type=sa.VARCHAR(length=20),
    #            server_default=None,
    #            existing_nullable=False)
    # op.alter_column('tenants', 'current_storage_bytes',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            existing_nullable=False)
    # op.alter_column('tenants', 'current_ai_tokens_used',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            existing_nullable=False)
    # op.alter_column('tenants', 'is_suspended',
    #            existing_type=sa.BOOLEAN(),
    #            server_default=None,
    #            existing_nullable=False)
    op.add_column('user_sessions', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('user_sessions', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('token_version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('mfa_secret', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('mfa_recovery_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'mfa_recovery_codes')
    op.drop_column('users', 'mfa_secret')
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'token_version')
    op.drop_column('user_sessions', 'city')
    op.drop_column('user_sessions', 'country')
    op.alter_column('tenants', 'is_suspended',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('tenants', 'current_ai_tokens_used',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'0'::bigint"),
               existing_nullable=False)
    op.alter_column('tenants', 'current_storage_bytes',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'0'::bigint"),
               existing_nullable=False)
    op.alter_column('tenants', 'db_connection_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'shared'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_audit_logs_module'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'correlation_id')
    op.drop_column('audit_logs', 'new_value')
    op.drop_column('audit_logs', 'old_value')
    op.drop_column('audit_logs', 'module')
    op.drop_column('audit_logs', 'severity')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_login_history_user_id'), table_name='login_history')
    op.drop_table('login_history')
    op.drop_index(op.f('ix_integration_logs_integration_id'), table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_created_at'), table_name='integration_logs')
    op.drop_table('integration_logs')
    op.drop_table('feature_rollouts')
    op.drop_table('feature_experiments')
    op.drop_index(op.f('ix_threat_intelligence_indicator_value'), table_name='threat_intelligence')
    op.drop_table('threat_intelligence')
    op.drop_index(op.f('ix_security_events_ip_address'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_type'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_created_at'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_table('integration_connections')
    op.drop_index(op.f('ix_feature_flags_key'), table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_table('compliance_reports')
    op.drop_table('automation_workflows')
    # ### end Alembic commands ###
