"""add_leads_table

Revision ID: 0ce9ac4e6622
Revises: 5fbc82b91bd4
Create Date: 2026-08-13 20:19:07.356344+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce9ac4e6622'
down_revision = '5fbc82b91bd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=False),
    sa.Column('business_email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('expected_users', sa.Integer(), nullable=True),
    sa.Column('expected_storage_gb', sa.Integer(), nullable=True),
    sa.Column('expected_data_volume', sa.String(length=100), nullable=True),
    sa.Column('ai_bi_requirements', sa.Text(), nullable=True),
    sa.Column('preferred_contact_time', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'contacted', 'demo', 'negotiation', 'approved', 'provisioning', 'active', 'rejected', name='lead_status'), nullable=False),
    sa.Column('source', sa.Enum('pricing_page', 'landing_page', 'referral', 'direct', name='lead_source'), nullable=False),
    sa.Column('lead_id', sa.String(length=30), nullable=False),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.String(length=200), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('demo_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id')
    )
    op.create_index(op.f('ix_leads_business_email'), 'leads', ['business_email'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.alter_column('tenants', 'provisioning_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'provisioning_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'none'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_business_email'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
