"""verify report bookmarks

Revision ID: 1f0274c9cdc9
Revises: a3218027390b
Create Date: 2026-08-18 06:33:43.154504+00:00

"""



# revision identifiers, used by Alembic.
revision = "1f0274c9cdc9"
down_revision = "a3218027390b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
