"""add_provisioning_status_to_tenants

Revision ID: 5fbc82b91bd4
Revises: 06937fd28d85
Create Date: 2026-08-13 19:58:08.470557+00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5fbc82b91bd4"
down_revision = "06937fd28d85"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenants",
        sa.Column(
            "provisioning_status",
            sa.String(length=20),
            server_default="none",
            nullable=False,
        ),
    )
    op.add_column("tenants", sa.Column("provisioning_error", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenants", "provisioning_error")
    op.drop_column("tenants", "provisioning_status")
    # ### end Alembic commands ###
