"""add tenant billing state fields

Revision ID: 3ed2ee02073a
Revises: 90230304ad9e
Create Date: 2026-08-08 21:45:49.492689+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3ed2ee02073a"
down_revision = "90230304ad9e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenants",
        sa.Column(
            "subscription_status",
            sa.String(length=50),
            nullable=False,
            server_default="active",
        ),
    )
    op.add_column(
        "tenants",
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "tenants", sa.Column("cancel_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "tenants",
        sa.Column("seats_purchased", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenants", "seats_purchased")
    op.drop_column("tenants", "cancel_at")
    op.drop_column("tenants", "current_period_end")
    op.drop_column("tenants", "subscription_status")
    # ### end Alembic commands ###
