"""Add storage models

Revision ID: cad1abc1cb9b
Revises: c884bdec6eb8
Create Date: 2026-08-01 10:24:05.554236+00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cad1abc1cb9b"
down_revision = "c884bdec6eb8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storage_buckets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("bucket_type", sa.String(length=50), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("region", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_storage_buckets_name"), "storage_buckets", ["name"], unique=True
    )
    op.create_table(
        "storage_backups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("is_automated", sa.Boolean(), nullable=False),
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_storage_backups_tenant_id"),
        "storage_backups",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "storage_lifecycle_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("bucket_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("target_bucket_id", sa.UUID(), nullable=True),
        sa.Column("condition_days", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["bucket_id"], ["storage_buckets.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_storage_lifecycle_policies_bucket_id"),
        "storage_lifecycle_policies",
        ["bucket_id"],
        unique=False,
    )
    op.create_table(
        "storage_activity_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_storage_activity_logs_created_at"),
        "storage_activity_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_storage_activity_logs_tenant_id"),
        "storage_activity_logs",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "storage_files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("bucket_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("file_type", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("is_encrypted", sa.Boolean(), nullable=False),
        sa.Column("is_malware_scanned", sa.Boolean(), nullable=False),
        sa.Column("download_count", sa.Integer(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["bucket_id"], ["storage_buckets.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_storage_files_bucket_id"), "storage_files", ["bucket_id"], unique=False
    )
    op.create_index(
        op.f("ix_storage_files_deleted_at"),
        "storage_files",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_storage_files_file_path"), "storage_files", ["file_path"], unique=False
    )
    op.create_index(
        op.f("ix_storage_files_owner_id"), "storage_files", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_storage_files_tenant_id"), "storage_files", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_storage_files_tenant_id"), table_name="storage_files")
    op.drop_index(op.f("ix_storage_files_owner_id"), table_name="storage_files")
    op.drop_index(op.f("ix_storage_files_file_path"), table_name="storage_files")
    op.drop_index(op.f("ix_storage_files_deleted_at"), table_name="storage_files")
    op.drop_index(op.f("ix_storage_files_bucket_id"), table_name="storage_files")
    op.drop_table("storage_files")
    op.drop_index(
        op.f("ix_storage_activity_logs_tenant_id"), table_name="storage_activity_logs"
    )
    op.drop_index(
        op.f("ix_storage_activity_logs_created_at"), table_name="storage_activity_logs"
    )
    op.drop_table("storage_activity_logs")
    op.drop_index(
        op.f("ix_storage_lifecycle_policies_bucket_id"),
        table_name="storage_lifecycle_policies",
    )
    op.drop_table("storage_lifecycle_policies")
    op.drop_index(op.f("ix_storage_backups_tenant_id"), table_name="storage_backups")
    op.drop_table("storage_backups")
    op.drop_index(op.f("ix_storage_buckets_name"), table_name="storage_buckets")
    op.drop_table("storage_buckets")
    # ### end Alembic commands ###
