"""Add report activities table

Revision ID: 78aad9e00737
Revises: 9bad8840ac6f
Create Date: 2026-08-18 06:42:16.100341+00:00

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "78aad9e00737"
down_revision = "9bad8840ac6f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_activities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_report_activities_id"), "report_activities", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_report_activities_report_id"),
        "report_activities",
        ["report_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_report_activities_tenant_id"),
        "report_activities",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_report_activities_user_id"),
        "report_activities",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_report_activities_user_id"), table_name="report_activities")
    op.drop_index(
        op.f("ix_report_activities_tenant_id"), table_name="report_activities"
    )
    op.drop_index(
        op.f("ix_report_activities_report_id"), table_name="report_activities"
    )
    op.drop_index(op.f("ix_report_activities_id"), table_name="report_activities")
    op.drop_table("report_activities")
    # ### end Alembic commands ###
