"""add charts table

Revision ID: 06937fd28d85
Revises: 6bd30796fa4c
Create Date: 2026-08-11 20:34:55.662282+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "06937fd28d85"
down_revision = "6bd30796fa4c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "charts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("chart_type", sa.String(length=50), nullable=False),
        sa.Column("configuration_json", sa.JSON(), nullable=False),
        sa.Column("visibility", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["dataset_id"], ["datasets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_charts_dataset_id"), "charts", ["dataset_id"], unique=False,
    )
    op.create_index(op.f("ix_charts_tenant_id"), "charts", ["tenant_id"], unique=False)
    op.create_index(
        op.f("ix_charts_workspace_id"), "charts", ["workspace_id"], unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_charts_workspace_id"), table_name="charts")
    op.drop_index(op.f("ix_charts_tenant_id"), table_name="charts")
    op.drop_index(op.f("ix_charts_dataset_id"), table_name="charts")
    op.drop_table("charts")
    # ### end Alembic commands ###
