"""Actually create report_bookmarks table

Revision ID: 9bad8840ac6f
Revises: 1f0274c9cdc9
Create Date: 2026-08-18 06:39:22.375316+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9bad8840ac6f"
down_revision = "1f0274c9cdc9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_bookmarks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_report_bookmarks_id"), "report_bookmarks", ["id"], unique=False,
    )
    op.create_index(
        op.f("ix_report_bookmarks_report_id"),
        "report_bookmarks",
        ["report_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_report_bookmarks_tenant_id"),
        "report_bookmarks",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_report_bookmarks_user_id"),
        "report_bookmarks",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_report_bookmarks_user_id"), table_name="report_bookmarks")
    op.drop_index(op.f("ix_report_bookmarks_tenant_id"), table_name="report_bookmarks")
    op.drop_index(op.f("ix_report_bookmarks_report_id"), table_name="report_bookmarks")
    op.drop_index(op.f("ix_report_bookmarks_id"), table_name="report_bookmarks")
    op.drop_table("report_bookmarks")
    # ### end Alembic commands ###
