"""Add export and email fields to ReportSchedule

Revision ID: d8f415553073
Revises: 20321007b006
Create Date: 2026-09-01 08:41:37.736630+00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d8f415553073"
down_revision = "20321007b006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "report_schedules", sa.Column("export_format", sa.String(), nullable=False)
    )
    op.add_column(
        "report_schedules", sa.Column("email_recipients", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("report_schedules", "email_recipients")
    op.drop_column("report_schedules", "export_format")
    # ### end Alembic commands ###
