"""Add DatasetAlert model

Revision ID: a4126d4b6cef
Revises: d8f415553073
Create Date: 2026-09-01 18:55:48.719970+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4126d4b6cef'
down_revision = 'd8f415553073'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('metric_column', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_alerts_dataset_id'), 'dataset_alerts', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_alerts_id'), 'dataset_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_dataset_alerts_tenant_id'), 'dataset_alerts', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dataset_alerts_tenant_id'), table_name='dataset_alerts')
    op.drop_index(op.f('ix_dataset_alerts_id'), table_name='dataset_alerts')
    op.drop_index(op.f('ix_dataset_alerts_dataset_id'), table_name='dataset_alerts')
    op.drop_table('dataset_alerts')
    # ### end Alembic commands ###
