"""Add tenant settings config columns

Revision ID: 6bd30796fa4c
Revises: 4ae3ff03084b
Create Date: 2026-08-10 14:57:48.857512+00:00

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6bd30796fa4c"
down_revision = "4ae3ff03084b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rental_contracts",
        "contract_type",
        existing_type=sa.VARCHAR(length=50),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "status",
        existing_type=sa.VARCHAR(length=50),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "start_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "billing_cycle",
        existing_type=sa.VARCHAR(length=20),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "base_price_monthly",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "annual_contract_value",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "annual_discount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "contracted_annual_amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "currency",
        existing_type=sa.VARCHAR(length=10),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "payment_terms",
        existing_type=sa.VARCHAR(length=50),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "support_tier",
        existing_type=sa.VARCHAR(length=50),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "sla_guarantee",
        existing_type=sa.VARCHAR(length=50),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "deployment_model",
        existing_type=sa.VARCHAR(length=100),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "resource_requests",
        "resource_type",
        existing_type=sa.VARCHAR(length=50),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "resource_requests",
        "status",
        existing_type=sa.VARCHAR(length=50),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "resource_requests",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "resource_requests",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.add_column(
        "tenants", sa.Column("data_connections_config", sa.JSON(), nullable=True),
    )
    op.add_column("tenants", sa.Column("integrations_config", sa.JSON(), nullable=True))
    op.add_column(
        "tenants", sa.Column("notifications_config", sa.JSON(), nullable=True),
    )
    op.add_column("tenants", sa.Column("advanced_config", sa.JSON(), nullable=True))
    op.alter_column(
        "tenants",
        "subscription_status",
        existing_type=sa.VARCHAR(length=50),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "tenants",
        "seats_purchased",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tenants",
        "seats_purchased",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "tenants",
        "subscription_status",
        existing_type=sa.VARCHAR(length=50),
        server_default=sa.text("'active'::character varying"),
        existing_nullable=False,
    )
    op.drop_column("tenants", "advanced_config")
    op.drop_column("tenants", "notifications_config")
    op.drop_column("tenants", "integrations_config")
    op.drop_column("tenants", "data_connections_config")
    op.alter_column(
        "resource_requests",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "resource_requests",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "resource_requests",
        "status",
        existing_type=sa.VARCHAR(length=50),
        server_default=sa.text("'submitted'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "resource_requests",
        "resource_type",
        existing_type=sa.VARCHAR(length=50),
        server_default=sa.text("'storage'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "deployment_model",
        existing_type=sa.VARCHAR(length=100),
        server_default=sa.text("'Dedicated Single-Tenant VPC'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "sla_guarantee",
        existing_type=sa.VARCHAR(length=50),
        server_default=sa.text("'99.99% Uptime SLA'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "support_tier",
        existing_type=sa.VARCHAR(length=50),
        server_default=sa.text("'24/7 Dedicated Engineering'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "payment_terms",
        existing_type=sa.VARCHAR(length=50),
        server_default=sa.text("'Annual Advance'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "currency",
        existing_type=sa.VARCHAR(length=10),
        server_default=sa.text("'USD'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "contracted_annual_amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=sa.text("'120000'::double precision"),
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "annual_discount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=sa.text("'30000'::double precision"),
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "annual_contract_value",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=sa.text("'150000'::double precision"),
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "base_price_monthly",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        server_default=sa.text("'12500'::double precision"),
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "billing_cycle",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'annual'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "start_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "status",
        existing_type=sa.VARCHAR(length=50),
        server_default=sa.text("'active'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "rental_contracts",
        "contract_type",
        existing_type=sa.VARCHAR(length=50),
        server_default=sa.text("'dedicated_system_rental'::character varying"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
