"""Add report bookmark

Revision ID: a3218027390b
Revises: 92e91260fa5b
Create Date: 2026-08-18 06:28:40.886356+00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a3218027390b"
down_revision = "92e91260fa5b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_tenant_workspace_dashboard",
        "dashboards",
        ["tenant_id", "workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_tenant_workspace_dataset",
        "datasets",
        ["tenant_id", "workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_tenant_workspace_report",
        "reports",
        ["tenant_id", "workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tenant_workspace_report", table_name="reports")
    op.drop_index("ix_tenant_workspace_dataset", table_name="datasets")
    op.drop_index("ix_tenant_workspace_dashboard", table_name="dashboards")
    # ### end Alembic commands ###
