"""add dashboard model

Revision ID: 3f1e5a230e9c
Revises: e2a19b8409ee
Create Date: 2026-08-07 20:36:30.304288+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3f1e5a230e9c"
down_revision = "e2a19b8409ee"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboards",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=True),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("layout_json", sa.JSON(), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("primary_dataset_id", sa.UUID(), nullable=True),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["primary_dataset_id"], ["datasets.id"], ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dashboards_tenant_id"), "dashboards", ["tenant_id"], unique=False,
    )
    op.create_index(
        op.f("ix_dashboards_workspace_id"), "dashboards", ["workspace_id"], unique=False,
    )
    # op.alter_column('tenants', 'db_connection_type',
    #            existing_type=sa.VARCHAR(length=20),
    #            server_default=None,
    #            existing_nullable=False)
    # op.alter_column('tenants', 'current_storage_bytes',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            existing_nullable=False)
    # op.alter_column('tenants', 'current_ai_tokens_used',
    #            existing_type=sa.BIGINT(),
    #            server_default=None,
    #            existing_nullable=False)
    # op.alter_column('tenants', 'is_suspended',
    #            existing_type=sa.BOOLEAN(),
    #            server_default=None,
    #            existing_nullable=False)
    # op.alter_column('user_sessions', 'country',
    #            existing_type=sa.VARCHAR(length=100),
    #            server_default=None,
    #            existing_nullable=True)
    # op.alter_column('user_sessions', 'city',
    #            existing_type=sa.VARCHAR(length=100),
    #            server_default=None,
    #            existing_nullable=True)
    # op.alter_column('users', 'token_version',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False)
    # op.alter_column('users', 'mfa_enabled',
    #            existing_type=sa.BOOLEAN(),
    #            server_default=None,
    #            existing_nullable=False)
    # op.alter_column('users', 'failed_login_attempts',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "failed_login_attempts",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "mfa_enabled",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "token_version",
        existing_type=sa.INTEGER(),
        server_default=sa.text("1"),
        existing_nullable=False,
    )
    op.alter_column(
        "user_sessions",
        "city",
        existing_type=sa.VARCHAR(length=100),
        server_default=sa.text("'Unknown'::character varying"),
        existing_nullable=True,
    )
    op.alter_column(
        "user_sessions",
        "country",
        existing_type=sa.VARCHAR(length=100),
        server_default=sa.text("'Unknown'::character varying"),
        existing_nullable=True,
    )
    op.alter_column(
        "tenants",
        "is_suspended",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "tenants",
        "current_ai_tokens_used",
        existing_type=sa.BIGINT(),
        server_default=sa.text("'0'::bigint"),
        existing_nullable=False,
    )
    op.alter_column(
        "tenants",
        "current_storage_bytes",
        existing_type=sa.BIGINT(),
        server_default=sa.text("'0'::bigint"),
        existing_nullable=False,
    )
    op.alter_column(
        "tenants",
        "db_connection_type",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'shared'::character varying"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_dashboards_workspace_id"), table_name="dashboards")
    op.drop_index(op.f("ix_dashboards_tenant_id"), table_name="dashboards")
    op.drop_table("dashboards")
    # ### end Alembic commands ###
