"""add billing models

Revision ID: 68596c43178a
Revises: 19292dc7ebf1
Create Date: 2026-07-31 20:32:35.337392+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "68596c43178a"
down_revision = "19292dc7ebf1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_activities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_billing_activities_tenant_id"),
        "billing_activities",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "paid", "pending", "failed", "refunded", "draft", name="invoicestatus",
            ),
            nullable=False,
        ),
        sa.Column("stripe_invoice_id", sa.String(length=255), nullable=True),
        sa.Column("pdf_url", sa.String(length=1024), nullable=True),
        sa.Column("billing_reason", sa.String(length=50), nullable=True),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invoice_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stripe_invoice_id"),
    )
    op.create_index(
        op.f("ix_invoices_tenant_id"), "invoices", ["tenant_id"], unique=False,
    )
    op.add_column(
        "tenants",
        sa.Column(
            "billing_cycle",
            sa.String(length=20),
            server_default="monthly",
            nullable=False,
        ),
    )
    op.add_column(
        "tenants", sa.Column("mrr", sa.Float(), server_default="0.0", nullable=False),
    )
    op.add_column(
        "tenants", sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenants", "trial_ends_at")
    op.drop_column("tenants", "mrr")
    op.drop_column("tenants", "billing_cycle")
    op.drop_index(op.f("ix_invoices_tenant_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(
        op.f("ix_billing_activities_tenant_id"), table_name="billing_activities",
    )
    op.drop_table("billing_activities")
    # ### end Alembic commands ###
